(cl:in-package collect_data-msg)
(cl:export '(X-VAL
          X
          Y-VAL
          Y
          Z-VAL
          Z
          ROLL-VAL
          ROLL
          PITCH-VAL
          PITCH
          YAW-VAL
          YAW
          GRIPPER-VAL
          GRIPPER
          QUATER_X-VAL
          QUATER_X
          QUATER_Y-VAL
          QUATER_Y
          QUATER_Z-VAL
          QUATER_Z
          QUATER_W-VAL
          QUATER_W
          CHX-VAL
          CHX
          CHY-VAL
          CHY
          CHZ-VAL
          CHZ
          VEL_L-VAL
          VEL_L
          VEL_R-VAL
          VEL_R
          HEIGHT-VAL
          HEIGHT
          HEAD_PIT-VAL
          HEAD_PIT
          HEAD_YAW-VAL
          HEAD_YAW
          TEMPFLOATDATA-VAL
          TEMPFLOATDATA
          TEMPINTDATA-VAL
          TEMPINTDATA
          MODE1-VAL
          MODE1
          MODE2-VAL
          MODE2
          TIMECOUNT-VAL
          TIMECOUNT
))